version: '3.8'
services:
  app:
    build: .
    container_name: wallet-service-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wallet-network

  db:
    image: postgres:13
    container_name: wallet-service-db
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - wallet-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    name: wallet-service-postgres-data

networks:
  wallet-network:
    name: wallet-service-network
    driver: bridge