spring:
  datasource:
    url: jdbc:postgresql://db:5432/wallet_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      validation-timeout: 5000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

logging:
  level:
    root: INFO
    com.wallet: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG