spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 50

server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20

logging:
  level:
    root: INFO
    com.wallet: INFO